// webview/src/components/Messages/blocks/tools/Grep.vue
<template>
  <ToolMessageWrapper
    tool-icon="codicon-grep"
    :tool-result="toolResult"
    :permission-state="permissionState"
    @allow="$emit('allow')"
    @deny="$emit('deny')"
  >
    <template #main>
      <span class="tool-label">Grep</span>
      <code v-if="pattern" class="pattern-text">{{ pattern }}</code>
    </template>

    <!-- 展开内容：显示搜索选项和结果 -->
    <template #expandable>
      <!-- 搜索选项 -->
      <div v-if="hasSearchOptions" class="options-section">
        <div class="options-grid">
          <div v-if="searchPath" class="option-item">
            <span class="codicon codicon-folder"></span>
            <span class="option-text">路径: {{ searchPath }}</span>
          </div>
          <div v-if="glob" class="option-item">
            <span class="codicon codicon-filter"></span>
            <span class="option-text">过滤: {{ glob }}</span>
          </div>
          <div v-if="fileType" class="option-item">
            <span class="codicon codicon-file-code"></span>
            <span class="option-text">类型: {{ fileType }}</span>
          </div>
          <div v-if="outputMode" class="option-item">
            <span class="codicon codicon-output"></span>
            <span class="option-text">模式: {{ outputMode }}</span>
          </div>
        </div>
      </div>

      <!-- 搜索标志 -->
      <div v-if="hasFlags" class="flags-section">
        <div class="detail-label">标志:</div>
        <div class="flags-list">
          <span v-if="caseInsensitive" class="flag-tag">
            <span class="codicon codicon-case-sensitive"></span>
            忽略大小写
          </span>
          <span v-if="multiline" class="flag-tag">
            <span class="codicon codicon-whole-word"></span>
            多行模式
          </span>
          <span v-if="showLineNumbers" class="flag-tag">
            <span class="codicon codicon-list-ordered"></span>
            显示行号
          </span>
          <span v-if="contextLines" class="flag-tag">
            <span class="codicon codicon-list-tree"></span>
            上下文: {{ contextLines }} 行
          </span>
          <span v-if="headLimit" class="flag-tag">
            <span class="codicon codicon-arrow-up"></span>
            限制: {{ headLimit }} 条
          </span>
        </div>
      </div>

      <!-- 搜索结果 -->
      <div v-if="resultFiles.length > 0" class="results-section">
        <div class="detail-label">
          <span>找到 {{ fileCount }} 个文件:</span>
        </div>
        <div class="file-list">
          <ToolFilePath
            v-for="(file, index) in resultFiles"
            :key="index"
            :file-path="file"
            class="file-item"
          />
        </div>
      </div>

      <!-- 错误内容 -->
      <ToolError :tool-result="toolResult" />
    </template>
  </ToolMessageWrapper>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import ToolMessageWrapper from './common/ToolMessageWrapper.vue';
import ToolError from './common/ToolError.vue';
import ToolFilePath from './common/ToolFilePath.vue';

interface Props {
  toolUse?: any;
  toolResult?: any;
  permissionState?: string;
}

const props = defineProps<Props>();

defineEmits<{
  allow: [];
  deny: [];
}>();

// 搜索模式
const pattern = computed(() => props.toolUse?.input?.pattern);

// 搜索选项
const searchPath = computed(() => props.toolUse?.input?.path);
const glob = computed(() => props.toolUse?.input?.glob);
const fileType = computed(() => props.toolUse?.input?.type);
const outputMode = computed(() => props.toolUse?.input?.output_mode);

// 搜索标志
const caseInsensitive = computed(() => props.toolUse?.input?.['-i']);
const multiline = computed(() => props.toolUse?.input?.multiline);
const showLineNumbers = computed(() => props.toolUse?.input?.['-n']);
const contextLines = computed(() => {
  return props.toolUse?.input?.['-A'] || props.toolUse?.input?.['-B'] || props.toolUse?.input?.['-C'];
});
const headLimit = computed(() => props.toolUse?.input?.head_limit);

// 判断是否有选项或标志
const hasSearchOptions = computed(() => {
  return searchPath.value || glob.value || fileType.value || outputMode.value;
});

const hasFlags = computed(() => {
  return caseInsensitive.value || multiline.value || showLineNumbers.value || contextLines.value || headLimit.value;
});

// 解析搜索结果
const resultFiles = computed(() => {
  if (!props.toolResult?.content) return [];

  const content = props.toolResult.content;

  // 如果是字符串，解析文件列表
  if (typeof content === 'string') {
    const lines = content.split('\n').filter(line => line.trim());
    // 过滤掉 "Found X files" 这样的统计行
    return lines.filter(line => !line.match(/^Found \d+ files?$/i));
  }

  return [];
});

const fileCount = computed(() => resultFiles.value.length);
</script>

<style scoped>
.tool-label {
  font-weight: 500;
  color: var(--vscode-foreground);
  font-size: 0.9em;
}

.pattern-text {
  font-family: var(--vscode-editor-font-family);
  color: var(--vscode-charts-purple);
  background-color: color-mix(in srgb, var(--vscode-charts-purple) 15%, transparent);
  padding: 2px 6px;
  border-radius: 3px;
  font-weight: 500;
  font-size: 0.9em;
}

.options-section,
.flags-section {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 4px 0;
  font-size: 0.85em;
}

.results-section {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding: 6px 0;
  font-size: 0.85em;
}

.detail-label {
  color: color-mix(in srgb, var(--vscode-foreground) 70%, transparent);
  font-weight: 500;
}

.options-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.option-item {
  display: flex;
  align-items: center;
  gap: 4px;
  color: var(--vscode-foreground);
}

.option-item .codicon {
  font-size: 12px;
  color: color-mix(in srgb, var(--vscode-foreground) 70%, transparent);
}

.option-text {
  font-family: var(--vscode-editor-font-family);
}

.flags-list {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.flag-tag {
  display: flex;
  align-items: center;
  gap: 4px;
  background-color: color-mix(in srgb, var(--vscode-charts-blue) 15%, transparent);
  color: var(--vscode-charts-blue);
  padding: 3px 8px;
  border-radius: 3px;
  font-weight: 500;
}

.flag-tag .codicon {
  font-size: 12px;
}

.file-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
}
</style>

// webview/src/components/Messages/blocks/tools/Grep/Grep.tsx
import { memo, useMemo } from 'react';
import { Icon } from '@/components/common';
import { ToolMessageWrapper, ToolError, ToolFilePath } from '../common';
import styles from './Grep.module.css';

interface GrepProps {
  toolUse?: any;
  toolResult?: any;
  toolUseResult?: any;
  permissionState?: string;
  onAllow?: () => void;
  onDeny?: () => void;
}

export const Grep = memo(function Grep({
  toolUse,
  toolResult,
  toolUseResult,
  permissionState,
  onAllow,
  onDeny
}: GrepProps) {
  const pattern = useMemo(() => toolUse?.input?.pattern, [toolUse?.input?.pattern]);
  const searchPath = useMemo(() => toolUse?.input?.path, [toolUse?.input?.path]);
  const glob = useMemo(() => toolUse?.input?.glob, [toolUse?.input?.glob]);
  const fileType = useMemo(() => toolUse?.input?.type, [toolUse?.input?.type]);
  const outputMode = useMemo(() => toolUse?.input?.output_mode, [toolUse?.input?.output_mode]);

  const caseInsensitive = useMemo(() => toolUse?.input?.['-i'], [toolUse?.input]);
  const multiline = useMemo(() => toolUse?.input?.multiline, [toolUse?.input?.multiline]);
  const showLineNumbers = useMemo(() => toolUse?.input?.['-n'], [toolUse?.input]);
  const contextLines = useMemo(() => {
    return toolUse?.input?.['-A'] || toolUse?.input?.['-B'] || toolUse?.input?.['-C'];
  }, [toolUse?.input]);
  const headLimit = useMemo(() => toolUse?.input?.head_limit, [toolUse?.input?.head_limit]);

  const hasSearchOptions = useMemo(() => {
    return searchPath || glob || fileType || outputMode;
  }, [searchPath, glob, fileType, outputMode]);

  const hasFlags = useMemo(() => {
    return caseInsensitive || multiline || showLineNumbers || contextLines || headLimit;
  }, [caseInsensitive, multiline, showLineNumbers, contextLines, headLimit]);

  const resultFiles = useMemo(() => {
    if (!toolResult?.content) return [];
    const content = toolResult.content;

    if (typeof content === 'string') {
      const lines = content.split('\n').filter(line => line.trim());
      return lines.filter(line => !line.match(/^Found \d+ files?$/i));
    }

    return [];
  }, [toolResult?.content]);

  const fileCount = useMemo(() => resultFiles.length, [resultFiles]);

  return (
    <ToolMessageWrapper
      toolIcon="codicon-grep"
      toolResult={toolResult}
      permissionState={permissionState}
      onAllow={onAllow}
      onDeny={onDeny}
      main={
        <>
          <span className={styles.toolLabel}>Grep</span>
          {pattern && <code className={styles.patternText}>{pattern}</code>}
        </>
      }
      expandable={
        <>
          {/* Search Options */}
          {hasSearchOptions && (
            <div className={styles.optionsSection}>
              <div className={styles.optionsGrid}>
                {searchPath && (
                  <div className={styles.optionItem}>
                    <Icon name="codicon-folder" />
                    <span className={styles.optionText}>路径: {searchPath}</span>
                  </div>
                )}
                {glob && (
                  <div className={styles.optionItem}>
                    <Icon name="codicon-filter" />
                    <span className={styles.optionText}>过滤: {glob}</span>
                  </div>
                )}
                {fileType && (
                  <div className={styles.optionItem}>
                    <Icon name="codicon-file-code" />
                    <span className={styles.optionText}>类型: {fileType}</span>
                  </div>
                )}
                {outputMode && (
                  <div className={styles.optionItem}>
                    <Icon name="codicon-output" />
                    <span className={styles.optionText}>模式: {outputMode}</span>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Flags */}
          {hasFlags && (
            <div className={styles.flagsSection}>
              <div className={styles.detailLabel}>标志:</div>
              <div className={styles.flagsList}>
                {caseInsensitive && (
                  <span className={styles.flagTag}>
                    <Icon name="codicon-case-sensitive" />
                    忽略大小写
                  </span>
                )}
                {multiline && (
                  <span className={styles.flagTag}>
                    <Icon name="codicon-whole-word" />
                    多行模式
                  </span>
                )}
                {showLineNumbers && (
                  <span className={styles.flagTag}>
                    <Icon name="codicon-list-ordered" />
                    显示行号
                  </span>
                )}
                {contextLines && (
                  <span className={styles.flagTag}>
                    <Icon name="codicon-list-tree" />
                    上下文: {contextLines} 行
                  </span>
                )}
                {headLimit && (
                  <span className={styles.flagTag}>
                    <Icon name="codicon-arrow-up" />
                    限制: {headLimit} 条
                  </span>
                )}
              </div>
            </div>
          )}

          {/* Results */}
          {resultFiles.length > 0 && (
            <div className={styles.resultsSection}>
              <div className={styles.detailLabel}>
                <span>找到 {fileCount} 个文件:</span>
              </div>
              <div className={styles.fileList}>
                {resultFiles.map((file, index) => (
                  <ToolFilePath key={index} filePath={file} />
                ))}
              </div>
            </div>
          )}

          {/* Error */}
          <ToolError toolResult={toolResult} />
        </>
      }
    />
  );
});
