// webview/src/components/Messages/blocks/tools/common/ToolMessageWrapper.vue
<template>
  <div class="message-wrapper">
    <!-- 自定义布局模式 -->
    <template v-if="isCustomLayout">
      <slot name="custom"></slot>
    </template>

    <!-- 标准布局模式 -->
    <template v-else>
      <!-- 主信息行 -->
      <div
        class="main-line"
        :class="{ 'is-expandable': hasExpandableContent }"
        @click="toggleExpand"
        @mouseenter="isHovered = true"
        @mouseleave="isHovered = false"
      >
        <!-- 工具图标 -->
        <button class="tool-icon-btn">
          <span
            v-if="!isHovered || !hasExpandableContent"
            class="codicon"
            :class="toolIcon"
          ></span>
          <span
            v-else-if="isExpanded"
            class="codicon codicon-fold"
          ></span>
          <span
            v-else
            class="codicon codicon-chevron-up-down"
          ></span>
        </button>

        <!-- 主内容 -->
        <div class="main-content">
          <slot name="main"></slot>
        </div>

        <!-- 状态指示器 -->
        <ToolStatusIndicator
          v-if="indicatorState"
          :state="indicatorState"
          class="status-indicator-trailing"
        />
      </div>

      <!-- 展开内容 -->
      <div v-if="hasExpandableContent && isExpanded" class="expandable-content">
        <slot name="expandable"></slot>
      </div>
    </template>

    <!-- 权限审批按钮（在最下方） -->
    <div v-if="permissionState === 'pending'" class="permission-actions">
      <button @click.stop="$emit('deny')" class="btn-reject">
        <span>Reject ⇧⌘⊗</span>
      </button>
      <button @click.stop="$emit('allow')" class="btn-accept">
        <span>Accept ⌘↩</span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, useSlots } from 'vue';
import ToolStatusIndicator from './ToolStatusIndicator.vue';

interface Props {
  toolIcon?: string;
  toolResult?: any;
  permissionState?: string;
  defaultExpanded?: boolean;
  isCustomLayout?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  defaultExpanded: false,
  isCustomLayout: false
});

defineEmits<{
  allow: [];
  deny: [];
}>();

const slots = useSlots();

// 检测是否有展开内容
// 注意：由于 v-if 的动态特性，需要同时检查 slot 和错误状态
const hasExpandableContent = computed(() => {
  return !!slots.expandable || !!props.toolResult?.is_error;
});

// 展开状态 - 使用 computed 来完全响应 defaultExpanded
const userToggled = ref(false);
const isExpanded = computed({
  get: () => {
    // 优先使用用户手动切换的状态
    if (userToggled.value) {
      return userToggledState.value;
    }
    // 否则根据 defaultExpanded 或 错误状态决定
    return props.defaultExpanded || !!props.toolResult?.is_error;
  },
  set: (value) => {
    userToggled.value = true;
    userToggledState.value = value;
  }
});

const userToggledState = ref(false);
const isHovered = ref(false);

// 状态计算
const indicatorState = computed<'success' | 'error' | 'pending' | null>(() => {
  if (props.toolResult?.is_error) return 'error';
  if (props.permissionState === 'pending') return 'pending';
  if (props.toolResult) return 'success';
  return null;
});

// 切换展开
function toggleExpand() {
  if (hasExpandableContent.value) {
    isExpanded.value = !isExpanded.value;
  }
}
</script>

<style scoped>
.message-wrapper {
  display: flex;
  flex-direction: column;
  padding: 0px 8px;
}

.main-line {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 3px 0;
  user-select: none;
}

.main-line.is-expandable {
  cursor: pointer;
}

.main-line.is-expandable:hover {
  background-color: color-mix(in srgb, var(--vscode-list-hoverBackground) 30%, transparent);
}

.tool-icon-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: none;
  border: none;
  padding: 2px;
  color: var(--vscode-foreground);
  width: 20px;
  height: 20px;
  flex-shrink: 0;
}

.tool-icon-btn .codicon {
  font-size: 16px;
}

.main-content {
  flex: 1;
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.status-indicator-trailing {
  margin-left: auto;
}

.expandable-content {
  padding: 4px 0 0px 16px;
  margin-left: 10px;
  border-left: 1px solid var(--vscode-panel-border);
}

/* 权限审批按钮 */
.permission-actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  padding: 8px 0 4px;
  margin-left: 26px;
}

.btn-reject,
.btn-accept {
  padding: 4px 12px;
  border-radius: 4px;
  font-size: 0.9em;
  cursor: pointer;
  border: 1px solid var(--vscode-button-border);
}

.btn-reject {
  background: var(--vscode-button-secondaryBackground);
  color: var(--vscode-button-secondaryForeground);
}

.btn-reject:hover {
  background: var(--vscode-button-secondaryHoverBackground);
}

.btn-accept {
  background: var(--vscode-button-background);
  color: var(--vscode-button-foreground);
}

.btn-accept:hover {
  background: var(--vscode-button-hoverBackground);
}
</style>

// webview/src/components/Messages/blocks/tools/common/ToolMessageWrapper/ToolMessageWrapper.tsx
import { memo, useState, useCallback, useMemo, ReactNode } from 'react';
import { Icon } from '@/components/common';
import { ToolStatusIndicator } from '../ToolStatusIndicator';
import styles from './ToolMessageWrapper.module.css';

interface ToolMessageWrapperProps {
  toolIcon?: string;
  toolResult?: any;
  permissionState?: string;
  defaultExpanded?: boolean;
  isCustomLayout?: boolean;
  className?: string;
  onAllow?: () => void;
  onDeny?: () => void;
  // Slots
  main?: ReactNode;
  expandable?: ReactNode;
  custom?: ReactNode;
}

export const ToolMessageWrapper = memo(function ToolMessageWrapper({
  toolIcon,
  toolResult,
  permissionState,
  defaultExpanded = false,
  isCustomLayout = false,
  className = '',
  onAllow,
  onDeny,
  main,
  expandable,
  custom
}: ToolMessageWrapperProps) {
  const [isHovered, setIsHovered] = useState(false);
  const [userToggled, setUserToggled] = useState(false);
  const [userToggledState, setUserToggledState] = useState(false);

  // Check if there is expandable content
  const hasExpandableContent = useMemo(() => {
    return !!expandable || !!toolResult?.is_error;
  }, [expandable, toolResult?.is_error]);

  // Computed expanded state
  const isExpanded = useMemo(() => {
    if (userToggled) {
      return userToggledState;
    }
    return defaultExpanded || !!toolResult?.is_error;
  }, [userToggled, userToggledState, defaultExpanded, toolResult?.is_error]);

  // Status indicator state
  const indicatorState = useMemo<'success' | 'error' | 'pending' | null>(() => {
    if (toolResult?.is_error) return 'error';
    if (permissionState === 'pending') return 'pending';
    if (toolResult) return 'success';
    return null;
  }, [toolResult, permissionState]);

  // Toggle expand
  const toggleExpand = useCallback(() => {
    if (hasExpandableContent) {
      setUserToggled(true);
      setUserToggledState(!isExpanded);
    }
  }, [hasExpandableContent, isExpanded]);

  // Handle allow click
  const handleAllow = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    onAllow?.();
  }, [onAllow]);

  // Handle deny click
  const handleDeny = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    onDeny?.();
  }, [onDeny]);

  return (
    <div className={`${styles.messageWrapper} ${className}`}>
      {/* Custom Layout Mode */}
      {isCustomLayout ? (
        custom
      ) : (
        /* Standard Layout Mode */
        <>
          {/* Main Line */}
          <div
            className={`${styles.mainLine} ${hasExpandableContent ? styles.isExpandable : ''}`}
            onClick={toggleExpand}
            onMouseEnter={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
          >
            {/* Tool Icon */}
            <button className={styles.toolIconBtn}>
              {(!isHovered || !hasExpandableContent) ? (
                <Icon name={toolIcon || 'codicon-tools'} />
              ) : isExpanded ? (
                <Icon name="codicon-fold" />
              ) : (
                <Icon name="codicon-chevron-up-down" />
              )}
            </button>

            {/* Main Content */}
            <div className={styles.mainContent}>
              {main}
            </div>

            {/* Status Indicator */}
            {indicatorState && (
              <ToolStatusIndicator
                state={indicatorState}
                className={styles.statusIndicatorTrailing}
              />
            )}
          </div>

          {/* Expandable Content */}
          {hasExpandableContent && isExpanded && (
            <div className={styles.expandableContent}>
              {expandable}
            </div>
          )}
        </>
      )}

      {/* Permission Actions */}
      {permissionState === 'pending' && (
        <div className={styles.permissionActions}>
          <button onClick={handleDeny} className={styles.btnReject}>
            <span>Reject ⇧⌘⊗</span>
          </button>
          <button onClick={handleAllow} className={styles.btnAccept}>
            <span>Accept ⌘↩</span>
          </button>
        </div>
      )}
    </div>
  );
});
