// webview/src/App.tsx
import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChatPage } from './pages';
import { SessionsPage } from './pages/SessionsPage';
import { useMessageBus, notifyUIReady, requestSessionList } from './hooks';

type PageType = 'chat' | 'sessions';

function App() {
  const [currentPage, setCurrentPage] = useState<PageType>('chat');

  // Initialize message bus
  useMessageBus();

  // Notify UI ready on mount
  useEffect(() => {
    notifyUIReady();
    requestSessionList();
  }, []);

  // Handle switch to chat (optionally with a session id)
  const handleSwitchToChat = useCallback((sessionId?: string) => {
    // If sessionId is provided, the session will be loaded by SessionsPage
    setCurrentPage('chat');
  }, []);

  // Handle switch to sessions
  const handleSwitchToSessions = useCallback(() => {
    setCurrentPage('sessions');
  }, []);

  return (
    <div className="w-full h-screen flex flex-col bg-vscode-bg text-vscode-fg font-[var(--vscode-font-family)] text-[length:var(--vscode-font-size)] overflow-hidden">
      <AnimatePresence mode="wait">
        {currentPage === 'chat' && (
          <motion.div
            key="chat"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.2, ease: 'easeOut' }}
            className="h-full"
          >
            <ChatPage onSwitchToSessions={handleSwitchToSessions} />
          </motion.div>
        )}

        {currentPage === 'sessions' && (
          <motion.div
            key="sessions"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            transition={{ duration: 0.2, ease: 'easeOut' }}
            className="h-full"
          >
            <SessionsPage onSwitchToChat={handleSwitchToChat} />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default App;

// webview/src/App.vue
<template>
  <div class="app-wrapper">
    <main class="app-main">
      <div class="page-container">
        <Motion
          :animate="pageAnimation"
          :transition="{ duration: 0.3, ease: 'easeOut' }"
          class="motion-wrapper"
        >
          <SessionsPage
            v-if="currentPage === 'sessions'"
            key="sessions"
            @switch-to-chat="handleSwitchToChat"
          />
          <ChatPage
            v-else-if="currentPage === 'chat'"
            key="chat"
            @switch-to-sessions="switchToPage('sessions')"
          />
          <!-- IconTestPage -->
          <!-- <IconTestPage
            v-else-if="currentPage === 'icontest'"
            key="icontest"
          /> -->
        </Motion>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { Motion } from 'motion-v';
import SessionsPage from './pages/SessionsPage.vue';
import ChatPage from './pages/ChatPage.vue';
import './styles/claude-theme.css';
// import IconTestPage from './pages/IconTestPage.vue';

const currentPage = ref<'sessions' | 'chat'>('sessions');
const pageAnimation = ref({ opacity: 1, x: 0 });

function switchToPage(page: 'sessions' | 'chat') {
  pageAnimation.value = { opacity: 0, x: 0 };

  setTimeout(() => {
    currentPage.value = page;
    if (page === 'sessions') {
      pageAnimation.value = { opacity: 0.7, x: -3 };
      setTimeout(() => {
        pageAnimation.value = { opacity: 1, x: 0 };
      }, 50);
    } else {
      pageAnimation.value = { opacity: 0.7, x: 3 };
      setTimeout(() => {
        pageAnimation.value = { opacity: 1, x: 0 };
      }, 50);
    }
  }, 0);
}

function handleSwitchToChat(sessionId?: string) {
  if (sessionId) {
    console.log('Switching to chat with session:', sessionId);
  }
  switchToPage('chat');
}
</script>

<style>
.app-wrapper {
  display: flex;
  flex-direction: column;
  height: 100vh;
  color: var(--vscode-editor-foreground);
}

.app-main {
  flex: 1;
  overflow: hidden;
}

.page-container {
  position: relative;
  height: 100%;
  width: 100%;
}

.motion-wrapper {
  height: 100%;
  width: 100%;
  display: flex;
  flex-direction: column;
}
</style>
