// webview/src/components/chat/InputExtraBox/InputExtraBox.tsx
import { memo, useMemo } from 'react';
import { TodoList, TodoItem as Todo } from '../../ui/TodoList';
import { FileEditedList, FileEdit } from '../../editor/FileEditedList';
import { MessageQueueList, QueuedMessage } from '../MessageQueueList';
import styles from './InputExtraBox.module.css';

interface InputExtraBoxProps {
  todos?: Todo[];
  filesEdited?: FileEdit[];
  queuedMessages?: QueuedMessage[];
  showTodos?: boolean;
  showFiles?: boolean;
  showQueue?: boolean;
  onTodoToggle?: (index: number) => void;
  onQueueRemove?: (messageId: string) => void;
  onQueueSendNow?: (messageId: string) => void;
}

export const InputExtraBox = memo(function InputExtraBox({
  todos = [],
  filesEdited = [],
  queuedMessages = [],
  showTodos = false,
  showFiles = false,
  showQueue = false,
  onTodoToggle,
  onQueueRemove,
  onQueueSendNow
}: InputExtraBoxProps) {
  // Internal display logic: show container only when any item needs to be shown
  const shouldShow = useMemo(() => {
    const hasTodos = showTodos && todos.length > 0;
    const hasFiles = showFiles && filesEdited.length > 0;
    const hasQueue = showQueue && queuedMessages.length > 0;
    return hasTodos || hasFiles || hasQueue;
  }, [showTodos, todos.length, showFiles, filesEdited.length, showQueue, queuedMessages.length]);

  // Show divider between Todo and Queue
  const shouldShowTodoQueueDivider = useMemo(() => {
    const hasTodos = showTodos && todos.length > 0;
    const hasQueue = showQueue && queuedMessages.length > 0;
    return hasTodos && hasQueue;
  }, [showTodos, todos.length, showQueue, queuedMessages.length]);

  // Show divider between Queue and Files
  const shouldShowQueueFilesDivider = useMemo(() => {
    const hasQueue = showQueue && queuedMessages.length > 0;
    const hasFiles = showFiles && filesEdited.length > 0;
    return hasQueue && hasFiles;
  }, [showQueue, queuedMessages.length, showFiles, filesEdited.length]);

  if (!shouldShow) return null;

  return (
    <div className={styles.inputExtraBox}>
      <div className={styles.toolbarSection}>
        <TodoList
          todos={todos}
          visible={showTodos}
          onTodoToggle={onTodoToggle}
        />

        {/* Divider between Todo and Queue */}
        {shouldShowTodoQueueDivider && (
          <div className={styles.divider} />
        )}

        <MessageQueueList
          queuedMessages={queuedMessages}
          visible={showQueue}
          onRemove={onQueueRemove}
          onSendNow={onQueueSendNow}
        />

        {/* Divider between Queue and Files */}
        {shouldShowQueueFilesDivider && (
          <div className={styles.divider} />
        )}

        <FileEditedList
          filesEdited={filesEdited}
          visible={showFiles}
        />
      </div>
    </div>
  );
});

export default InputExtraBox;

// webview/src/components/InputExtraBox.vue
<template>
  <div v-if="shouldShow" style="padding: 0px 8px;">
    <div class="toolbar-section">
      <TodoList
        :todos="todos"
        :visible="showTodos"
        @todo-toggle="$emit('todoToggle', $event)"
      />
      <!-- 分割线 - Todo 和 Queue 之间 -->
      <div
        v-if="shouldShowTodoQueueDivider"
        style="height: 1px; background: color-mix(in srgb, var(--vscode-input-border, var(--vscode-widget-border)) 40%, transparent); margin: 2px -5px;"
      />
      <MessageQueueList
        :queued-messages="queuedMessages"
        :visible="showQueue"
        @remove="$emit('queueRemove', $event)"
        @send-now="$emit('queueSendNow', $event)"
      />
      <!-- 分割线 - Queue 和 Files 之间 -->
      <div
        v-if="shouldShowQueueFilesDivider"
        style="height: 1px; background: color-mix(in srgb, var(--vscode-input-border, var(--vscode-widget-border)) 40%, transparent); margin: 2px -5px;"
      />
      <FileEditedList
        :files-edited="filesEdited"
        :visible="showFiles"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import TodoList from './TodoList.vue'
import FileEditedList from './FileEditedList.vue'
import MessageQueueList from './MessageQueueList.vue'
import type { Todo, FileEdit } from '../../types/toolbar'
import type { QueuedMessage } from '../../types/queue'

interface Props {
  todos?: Todo[]
  filesEdited?: FileEdit[]
  queuedMessages?: QueuedMessage[]
  showTodos?: boolean
  showFiles?: boolean
  showQueue?: boolean
}

interface Emits {
  (e: 'todoToggle', index: number): void
  (e: 'queueRemove', messageId: string): void
  (e: 'queueSendNow', messageId: string): void
}

const props = withDefaults(defineProps<Props>(), {
  todos: () => [],
  filesEdited: () => [],
  queuedMessages: () => [],
  showTodos: false,
  showFiles: false,
  showQueue: false
})

defineEmits<Emits>()

// 内部显示逻辑：当有任一项需要显示时才显示整个容器
const shouldShow = computed(() => {
  const hasTodos = props.showTodos && props.todos.length > 0
  const hasFiles = props.showFiles && props.filesEdited.length > 0
  const hasQueue = props.showQueue && props.queuedMessages.length > 0
  return hasTodos || hasFiles || hasQueue
})

// Todo 与 Queue 之间的分割线
const shouldShowTodoQueueDivider = computed(() => {
  const hasTodos = props.showTodos && props.todos.length > 0
  const hasQueue = props.showQueue && props.queuedMessages.length > 0
  return hasTodos && hasQueue
})

// Queue 与 Files 之间的分割线
const shouldShowQueueFilesDivider = computed(() => {
  const hasQueue = props.showQueue && props.queuedMessages.length > 0
  const hasFiles = props.showFiles && props.filesEdited.length > 0
  return hasQueue && hasFiles
})
</script>
