// webview/src/components/Messages/blocks/TextBlock.vue
<template>
  <div class="text-block">
    <div class="text-content" v-html="formattedText"></div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { marked } from 'marked';
import type { ContentBlock } from '../../../../types/messages';

interface Props {
  block: ContentBlock;
  streaming?: boolean;
}

const props = defineProps<Props>();

// 配置 marked
marked.setOptions({
  breaks: true,        // 支持 GFM 换行
  gfm: true,          // 启用 GitHub Flavored Markdown
  headerIds: false,   // 不生成标题 ID
  mangle: false,      // 不混淆邮箱地址
});

const formattedText = computed(() => {
  if (!props.block.text) return '';

  try {
    // 使用 marked 解析 markdown
    return marked.parse(props.block.text, { async: false }) as string;
  } catch (error) {
    console.error('Markdown 解析失败:', error);
    // 降级：返回纯文本
    return props.block.text.replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
});
</script>

<style scoped>
.text-block {
  word-wrap: break-word;
  line-height: 1.5;
}

.text-content {
  /* marked 生成的 HTML 将使用父组件 (AssistantMessage) 的 markdown 样式 */
  user-select: text;
}
</style>

// webview/src/components/Messages/blocks/TextBlock/TextBlock.tsx
import React, { memo, useMemo } from 'react';
import { marked } from 'marked';
import type { ContentBlock } from '../../../../types/messages';
import styles from './TextBlock.module.css';

interface TextBlockProps {
  block: ContentBlock;
  streaming?: boolean;
}

// Configure marked
marked.setOptions({
  breaks: true,        // Support GFM line breaks
  gfm: true,          // Enable GitHub Flavored Markdown
});

export const TextBlock = memo(function TextBlock({
  block,
  streaming = false
}: TextBlockProps) {
  const formattedText = useMemo(() => {
    if (!block.text) return '';

    try {
      return marked.parse(block.text, { async: false }) as string;
    } catch (error) {
      console.error('Markdown parsing failed:', error);
      // Fallback: return escaped text
      return block.text.replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }
  }, [block.text]);

  return (
    <div className={styles.textBlock}>
      <div
        className={styles.textContent}
        dangerouslySetInnerHTML={{ __html: formattedText }}
      />
      {streaming && <span className={styles.streamingCursor}>|</span>}
    </div>
  );
});

export default TextBlock;
